run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: false
  issues-exclude-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
  issues-exclude-dirs:
    - bin
    - vendor
    - var
    - tmp
    - .cache
    - .vendor.protogen
    - swagger-ui

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  goconst:
    min-len:         2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - unparam
    - unconvert
    - tparallel
    - whitespace
    - testpackage
    - goimports
    - tagalign
    - gosec
    - ineffassign
    - typecheck
    - unused
    - sqlclosecheck
    - sloglint
    - reassign
    - protogetter
    - prealloc
    - perfsprint
    - paralleltest
    - nosprintfhostport
    - nolintlint
    - noctx
    - nlreturn
    - nilnil
    - nilerr
    - nestif
    - misspell
    - mirror
    - makezero
    - gofumpt
    - gocritic
    - gocognit
    - gci
    - durationcheck
    - dupword
    - dupl
    - bodyclose

issues:
  exclude-use-default: false
  exclude:
    - G104
    - exported func .* returns unexported type .*, which can be annoying to use
    - should have a package comment
    - don't use an underscore in package name
