addr: ":50052"
network: "tcp"

level: -4
# LevelDebug Level = -4
# LevelInfo  Level = 0
# LevelWarn  Level = 4
# LevelError Level = 8
configlogger: "prod"
# "prod" print log in json format
# "dev" print log in text format
