services:
  db:
    container_name: pg_chat
    image: postgres:16.3-alpine3.20
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/pg_data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${DB_USER}",
          "-d",
          "${DB_NAME}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  migrations:
    container_name: migrate_chat
    image: migrate/migrate
    volumes:
     - ./internal/migrations:/migrations
    depends_on:
      - db
    env_file:
      - .env
    entrypoint:
      [
        "migrate",
        "-path=migrations",
        "-database=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable",
        "up"
      ]
    restart: on-failure

volumes:
  db:
  migrations: