CREATE TABLE IF NOT EXISTS chats (
    id SERIAL PRIMARY KEY,
    usernames TEXT[] NOT NULL
);

CREATE TABLE chat_messages (
    id SERIAL PRIMARY KEY,
    chat_id INTEGER NOT NULL,
    receiver VARCHAR(255) NOT NULL,
    text_message TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE
);